version: '3.8'
services:
  server:
    build:
      context: .
    restart: always
    environment:
      SPRING_DATASOURCE_DRUID_MASTER_URL: jdbc:mysql://mysql:3306/ry-vue?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      SPRING_REDIS_HOST: redis
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
    depends_on:
      - mysql
    networks:
      - server

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ry-vue
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - server

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    depends_on:
      - mysql
    networks:
      - server

volumes:
  mysql_data:
  redis_data:
  
networks:
  server:
    driver: bridge
